# Generated by Django 4.2.1 on 2023-06-01 06:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statuscode',
            name='created_at',
        ),
        migrations.AddField(
            model_name='statuscode',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время'),
        ),
    ]
